#!/usr/bin/env php
<?php

use Bpzr\EntityAdapter\Command\EntityAdapterCheckCommand;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$app = new Application('Entity adapter', '1.0.0');

$app->add(new EntityAdapterCheckCommand());

$app->run();