#!/usr/bin/env php
<?php

use Bpzr\EntityAdapter\Command\EntityAdapterCheckCommand;
use Symfony\Component\Console\Application;

require_once 'vendor/autoload.php';

$app = new Application('Entity adapter');

$app->add(new EntityAdapterCheckCommand());

$app->run();